DROP INDEX IF EXISTS dm3_identity.idx_person_groups_name;
DROP INDEX IF EXISTS dm3_identity.idx_credentials_status;
DROP INDEX IF EXISTS dm3_identity.idx_credentials_type;
DROP INDEX IF EXISTS dm3_identity.idx_persons_updated;
DROP INDEX IF EXISTS dm3_identity.idx_persons_status;
DROP INDEX IF EXISTS dm3_identity.idx_persons_department;
DROP INDEX IF EXISTS dm3_identity.idx_persons_email;
DROP INDEX IF EXISTS dm3_identity.idx_persons_name;
DROP TABLE IF EXISTS dm3_identity.person_group_members CASCADE;
DROP TABLE IF EXISTS dm3_identity.person_groups CASCADE;
ALTER TABLE dm3_identity.credentials DROP COLUMN IF EXISTS updated_at;
