LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := RF_PN5180
LOCAL_CFLAGS := -DANDROID_NDK  -DDEBUG_MODE -DBUILD_LIB -DANDROID_DEVICE
LOCAL_LDLIBS:= -llog
LOCAL_SRC_FILES := \
		rf.c DevRf.c Common_Uart.c
include $(BUILD_SHARED_LIBRARY) 
