/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duali_subscreen_SubScreen */

#ifndef _Included_com_duali_subscreen_SubScreen
#define _Included_com_duali_subscreen_SubScreen
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_duali_subscreen_SubScreen_init
        (JNIEnv *, jclass clazz);

JNIEXPORT void JNICALL Java_com_duali_subscreen_SubScreen_led
        (JNIEnv *env, jclass clazz, int direct, int color);


JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_signpad
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_ledTest
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_relayTest
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_COMTest
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_CASHBOXTest
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_QRTest
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_QRTestAging
        (JNIEnv *, jclass clazz);

JNIEXPORT int JNICALL Java_com_duali_subscreen_SubScreen_QRClose
        (JNIEnv *, jclass clazz);

JNIEXPORT void JNICALL Java_com_duali_subscreen_SubScreen_LCDclose
        (JNIEnv *, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
