// Package docs exposes the OpenAPI spec generated by `make swag` so any service
// that wants to serve /openapi.json can embed the same bytes at build time.
//
// The .json/.yaml/docs.go files in this directory are generated by swaggo/swag
// (see ../Makefile:swag). They are committed to the repo so the spec is
// reviewable in PRs; CI runs `make swag-check` to catch drift between the
// annotations and the committed spec.
package docs

import _ "embed"

// SwaggerJSON is the OpenAPI 2.0 spec as JSON, ready to be served as
// application/json to an API explorer like Scalar, Redoc, or Swagger UI.
//
//go:embed swagger.json
var SwaggerJSON []byte

// SwaggerYAML is the same spec in YAML form. Kept embedded because it's
// convenient for CLI tooling (e.g. openapi-generator) that prefers YAML.
//
//go:embed swagger.yaml
var SwaggerYAML []byte
