#!/usr/bin/env bash
# Write the deploy .env file from GitLab CI/CD variables.
#
# Used by .gitlab-ci.yml before every docker compose invocation. Replaces
# the earlier approach of copying /home/gitlab-runner/.env.dm3 from the
# runner host — secrets now live in GitLab project variables
# (Settings → CI/CD → Variables) so rotation is auditable and maintained
# in a single place.
#
# This script:
#   * Fails fast if any required secret is unset or empty.
#   * Writes .env with 0600 perms (umask 077 before creation).
#   * Expands sensible defaults for non-secret values that the prod
#     compose file interpolates, so we don't rely on compose's own
#     ${VAR:-default} fallbacks.
#
# Callers are expected to rm -f .env at job exit (trap in CI script).

set -euo pipefail

# Required — must be set as protected, masked CI variables.
: "${DB_PASSWORD:?DB_PASSWORD must be set in GitLab CI/CD variables}"
: "${JWT_SECRET:?JWT_SECRET must be set in GitLab CI/CD variables}"
: "${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD must be set in GitLab CI/CD variables}"
: "${BOOTSTRAP_SECRET:?BOOTSTRAP_SECRET must be set in GitLab CI/CD variables}"
: "${CCTV_CREDENTIAL_KEY:?CCTV_CREDENTIAL_KEY must be set in GitLab CI/CD variables}"

umask 077
cat > .env <<EOF
# Generated by scripts/write-ci-env.sh during CI — DO NOT COMMIT.
# Source of truth: GitLab project Settings → CI/CD → Variables.
DB_NAME=${DB_NAME:-dm3}
DB_USER=${DB_USER:-dm3}
DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
MINIO_ROOT_USER=${MINIO_ROOT_USER:-dm3admin}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
BOOTSTRAP_SECRET=${BOOTSTRAP_SECRET}
KNOWN_APP_SIGNATURES=${KNOWN_APP_SIGNATURES:-}
CCTV_CREDENTIAL_KEY=${CCTV_CREDENTIAL_KEY}
MEDIAMTX_API_USER=${MEDIAMTX_API_USER:-dm3admin}
MEDIAMTX_API_PASS=${MEDIAMTX_API_PASS:-}
MEDIAMTX_STREAM_USER=${MEDIAMTX_STREAM_USER:-dm3stream}
MEDIAMTX_STREAM_PASS=${MEDIAMTX_STREAM_PASS:-}
MEDIAMTX_WHEP_BASE=${MEDIAMTX_WHEP_BASE:-https://dm3-cctv.demasterpro.com}
MEDIAMTX_HLS_BASE=${MEDIAMTX_HLS_BASE:-https://dm3-cctv.demasterpro.com}
API_URL=${API_URL:-https://dm3-api.demasterpro.com}
MQTT_WS_URL=${MQTT_WS_URL:-wss://dm3-mqtt.demasterpro.com/mqtt}
CORS_ORIGIN=${CORS_ORIGIN:-https://dm3.demasterpro.com}
EOF
chmod 600 .env

echo "[write-ci-env] wrote .env ($(wc -l < .env | tr -d ' ') lines, perms $(stat -c '%a' .env 2>/dev/null || stat -f '%Lp' .env))"
