package main

import (
	"net/http"

	"github.com/duali/dm3-backend/docs"
	"github.com/duali/dm3-backend/pkg/httputil"
)

// ServeOpenAPISpec returns the embedded OpenAPI 2.0 spec as application/json.
// This is the feed for the in-app Scalar viewer at /settings/api-docs. The
// route is mounted inside the `api_integration` plugin-gated group so tenants
// without the integration plugin can't see the spec either.
//
// The spec is generated by `make swag` from swaggo annotations on handler
// functions and committed to backend/docs/. CI runs `make swag-check` to catch
// drift between code and spec.
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	if len(docs.SwaggerJSON) == 0 {
		httputil.Error(w, http.StatusServiceUnavailable, "openapi spec not generated; run `make swag`")
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=60")
	_, _ = w.Write(docs.SwaggerJSON)
}
