import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css';
import { ArrowLeft, BookOpen, KeyRound } from 'lucide-react';
import { Button } from '@dm3/ui';
import { apiFetch } from '@/lib/api';

// ApiDocsPage renders the live OpenAPI spec generated from backend handler
// annotations via the Scalar API Reference component. The spec is served by
// auth-svc at GET /api/v1/openapi.json and is regenerated by `make swag` so
// these docs always match the deployed backend.
//
// The endpoint is gated by the `api_integration` plugin — the page is only
// reachable when the plugin is enabled for the tenant, so a 403 here
// indicates the plugin was turned off mid-session.
export function ApiDocsPage() {
  const { t } = useTranslation('settings');
  const navigate = useNavigate();
  const [spec, setSpec] = useState<Record<string, unknown> | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    apiFetch<Record<string, unknown>>('/api/v1/openapi.json')
      .then((data) => {
        if (!cancelled) setSpec(data);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        const message = err instanceof Error ? err.message : 'Failed to load API spec';
        setError(message);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="flex h-full min-h-0 flex-col overflow-hidden">
      <div className="shrink-0 border-b border-border p-6 pb-5">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/settings/api-tokens')}
            data-testid="apidocs-button-back"
          >
            <ArrowLeft size={16} />
          </Button>
          <div className="flex-1">
            <h1 className="flex items-center gap-2 text-[18px] font-semibold text-foreground">
              <BookOpen size={18} className="text-secure" />
              {t('apiDocs.title', 'API Documentation')}
            </h1>
            <p className="text-[13px] text-muted-foreground">
              {t(
                'apiDocs.description',
                'Live reference auto-generated from the deployed backend. Use these endpoints with any API token issued on this tenant.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => navigate('/settings/api-tokens')}
            data-testid="apidocs-button-manage-tokens"
          >
            <KeyRound size={14} className="mr-1.5" />
            {t('apiDocs.manageTokens', 'Manage tokens')}
          </Button>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto">
        {error ? (
          <div className="mx-auto max-w-2xl p-6">
            <div className="rounded-md border border-destructive/30 bg-destructive/10 p-4 text-[13px] text-destructive">
              {t('apiDocs.loadError', 'Failed to load API spec:')} {error}
            </div>
          </div>
        ) : spec ? (
          <ApiReferenceReact
            configuration={{
              content: spec,
              theme: 'default',
              darkMode: true,
              hideDarkModeToggle: true,
              hideDownloadButton: false,
              layout: 'modern',
              hideClientButton: false,
            }}
          />
        ) : (
          <div className="p-6 text-[13px] text-muted-foreground">
            {t('apiDocs.loading', 'Loading API reference…')}
          </div>
        )}
      </div>
    </div>
  );
}
